/**
 * Zoological Catalog & Field Guide Reference
 * teamLab Wildlife Living Sanctuary (Mobile Scanner)
 */

export const WILDLIFE_CATALOG = [
  {
    id_template: 'tiger',
    name: 'Royal Bengal Tiger',
    scientificName: 'Panthera tigris tigris',
    category: 'predator',
    diet: 'Apex Carnivore',
    habitat: 'Sundarbans Mangroves & Dense Jungles',
    conservationStatus: 'Endangered',
    rarity: 'legendary',
    isApex: true,
    scale: 1.35,
    archetype: 'tiger',
    color: '#f97316',
    secondaryColor: '#18181b',
    accentColor: '#ffffff',
    emissiveColor: '#ffedd5',
    auraColor: '#f97316',
    baseStats: { speedKmH: 65, weightKg: 230, lifespanYears: 16 },
    description: 'The undisputed lord of the Asian jungle. Solitary, stealthy, and possessing crushing bite force.'
  },
  {
    id_template: 'lion',
    name: 'African Lion',
    scientificName: 'Panthera leo',
    category: 'predator',
    diet: 'Apex Carnivore',
    habitat: 'Sub-Saharan Savannahs & Open Grasslands',
    conservationStatus: 'Vulnerable',
    rarity: 'legendary',
    isApex: true,
    scale: 1.4,
    archetype: 'lion',
    color: '#d97706',
    secondaryColor: '#451a03',
    accentColor: '#fef3c7',
    emissiveColor: '#fed7aa',
    auraColor: '#f59e0b',
    baseStats: { speedKmH: 80, weightKg: 210, lifespanYears: 14 },
    description: 'The iconic King of the Savannah. Males flaunt massive dark manes signifying dominance and vitality.'
  },
  {
    id_template: 'snow_leopard',
    name: 'Snow Leopard',
    scientificName: 'Panthera uncia',
    category: 'predator',
    diet: 'Carnivore',
    habitat: 'Himalayan Cliffs & High Alpine Tundra',
    conservationStatus: 'Vulnerable',
    rarity: 'legendary',
    isApex: true,
    scale: 1.25,
    archetype: 'snow_leopard',
    color: '#cbd5e1',
    secondaryColor: '#334155',
    accentColor: '#f8fafc',
    emissiveColor: '#e0f2fe',
    auraColor: '#38bdf8',
    baseStats: { speedKmH: 64, weightKg: 55, lifespanYears: 18 },
    description: 'The elusive "Ghost of the Mountains." Master of steep crags with massive furry snowshoe paws.'
  },
  {
    id_template: 'wolf',
    name: 'Alpha Timber Wolf',
    scientificName: 'Canis lupus',
    category: 'predator',
    diet: 'Pack Carnivore',
    habitat: 'Boreal Taiga & Mountain Wilderness',
    conservationStatus: 'Least Concern',
    rarity: 'legendary',
    isApex: true,
    scale: 1.25,
    archetype: 'wolf',
    color: '#94a3b8',
    secondaryColor: '#1e293b',
    accentColor: '#f1f5f9',
    emissiveColor: '#e2e8f0',
    auraColor: '#a855f7',
    baseStats: { speedKmH: 60, weightKg: 58, lifespanYears: 13 },
    description: 'Sovereign leader of the northern pack. Armed with tireless stamina and keen olfactory intelligence.'
  },
  {
    id_template: 'panther',
    name: 'Black Panther',
    scientificName: 'Panthera onca',
    category: 'predator',
    diet: 'Apex Carnivore',
    habitat: 'Amazon Rainforest & Deep River Basins',
    conservationStatus: 'Near Threatened',
    rarity: 'legendary',
    isApex: true,
    scale: 1.3,
    archetype: 'panther',
    color: '#18181b',
    secondaryColor: '#09090b',
    accentColor: '#10b981',
    emissiveColor: '#27272a',
    auraColor: '#10b981',
    baseStats: { speedKmH: 70, weightKg: 100, lifespanYears: 15 },
    description: 'Melanistic phantom of the tropical canopy. Possesses the strongest jaw of any big cat.'
  },
  {
    id_template: 'elephant',
    name: 'African Bush Elephant',
    scientificName: 'Loxodonta africana',
    category: 'megaherbivore',
    diet: 'Megaherbivore',
    habitat: 'African Woodlands & Dry Scrublands',
    conservationStatus: 'Endangered',
    rarity: 'rare',
    isApex: false,
    scale: 1.85,
    archetype: 'elephant',
    color: '#64748b',
    secondaryColor: '#475569',
    accentColor: '#fef08a',
    emissiveColor: '#94a3b8',
    auraColor: '#06b6d4',
    baseStats: { speedKmH: 40, weightKg: 6000, lifespanYears: 70 },
    description: 'The monumental titan of terrestrial wildlife. Revered for matriarchal wisdom and curved ivory.'
  },
  {
    id_template: 'bear',
    name: 'Grizzly Bear',
    scientificName: 'Ursus arctos horribilis',
    category: 'predator',
    diet: 'Apex Omnivore',
    habitat: 'Alpine Valleys, Coastal Forests & Tundra',
    conservationStatus: 'Least Concern',
    rarity: 'rare',
    isApex: false,
    scale: 1.5,
    archetype: 'bear',
    color: '#78350f',
    secondaryColor: '#451a03',
    accentColor: '#d97706',
    emissiveColor: '#92400e',
    auraColor: '#d97706',
    baseStats: { speedKmH: 56, weightKg: 380, lifespanYears: 25 },
    description: 'Identifiable by a prominent muscular shoulder hump powering ferocious speed and river fishing.'
  },
  {
    id_template: 'stag',
    name: 'Majestic Red Deer Stag',
    scientificName: 'Cervus elaphus',
    category: 'herbivore',
    diet: 'Herbivore',
    habitat: 'Ancient Highland Woods & Misty Glades',
    conservationStatus: 'Least Concern',
    rarity: 'rare',
    isApex: false,
    scale: 1.35,
    archetype: 'stag',
    color: '#b45309',
    secondaryColor: '#78350f',
    accentColor: '#fef3c7',
    emissiveColor: '#d97706',
    auraColor: '#10b981',
    baseStats: { speedKmH: 72, weightKg: 240, lifespanYears: 20 },
    description: 'Monarch of highland glens. Crowned with magnificent branching multi-tined antlers grown anew.'
  },
  {
    id_template: 'crocodile',
    name: 'Nile Crocodile',
    scientificName: 'Crocodylus niloticus',
    category: 'reptile',
    diet: 'Apex Carnivore',
    habitat: 'Freshwater Basins, Mangroves & Swamps',
    conservationStatus: 'Least Concern',
    rarity: 'rare',
    isApex: false,
    scale: 1.45,
    archetype: 'crocodile',
    color: '#365314',
    secondaryColor: '#1a2e05',
    accentColor: '#a3e635',
    emissiveColor: '#4d7c0f',
    auraColor: '#84cc16',
    baseStats: { speedKmH: 30, weightKg: 750, lifespanYears: 70 },
    description: 'Prehistoric apex survivor armored with keeled scutes and devastating hydraulic bite force.'
  },
  {
    id_template: 'cheetah',
    name: 'African Cheetah',
    scientificName: 'Acinonyx jubatus',
    category: 'predator',
    diet: 'Carnivore',
    habitat: 'Open Plains & Semi-Arid Steppes',
    conservationStatus: 'Vulnerable',
    rarity: 'common',
    isApex: false,
    scale: 1.2,
    archetype: 'cheetah',
    color: '#eab308',
    secondaryColor: '#713f12',
    accentColor: '#fef9c3',
    emissiveColor: '#facc15',
    auraColor: '#eab308',
    baseStats: { speedKmH: 112, weightKg: 52, lifespanYears: 12 },
    description: 'Fastest land mammal on Earth. Accelerating from 0 to 100 km/h in 3 seconds with flexible spine.'
  },
  {
    id_template: 'zebra',
    name: 'Plains Zebra',
    scientificName: 'Equus quagga',
    category: 'herbivore',
    diet: 'Herbivore',
    habitat: 'Savannah Grasslands & Woodlands',
    conservationStatus: 'Near Threatened',
    rarity: 'common',
    isApex: false,
    scale: 1.25,
    archetype: 'zebra',
    color: '#f8fafc',
    secondaryColor: '#09090b',
    accentColor: '#1e293b',
    emissiveColor: '#e2e8f0',
    auraColor: '#38bdf8',
    baseStats: { speedKmH: 68, weightKg: 320, lifespanYears: 25 },
    description: 'Famous for black and white dazzle camouflage confusing predators during great savannah migrations.'
  },
  {
    id_template: 'eagle',
    name: 'Golden Eagle',
    scientificName: 'Aquila chrysaetos',
    category: 'raptor',
    diet: 'Apex Raptor',
    habitat: 'Rugged Mountains, Cliffs & High Plateaus',
    conservationStatus: 'Least Concern',
    rarity: 'common',
    isApex: false,
    scale: 1.3,
    archetype: 'eagle',
    color: '#713f12',
    secondaryColor: '#ca8a04',
    accentColor: '#fef08a',
    emissiveColor: '#eab308',
    auraColor: '#f59e0b',
    baseStats: { speedKmH: 240, weightKg: 5.5, lifespanYears: 30 },
    description: 'Supreme feathered hunter of mountain heights, diving at speeds exceeding 240 km/h with talons.'
  }
];

export function findAnimalById(id) {
  if (!id) return null;
  // Match exact ID or ID prefix/archetype
  const found = WILDLIFE_CATALOG.find(
    (w) => id === w.id || id.includes(w.id_template) || id.toLowerCase().includes(w.archetype)
  );
  return found || WILDLIFE_CATALOG[0];
}
